spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: msclientes-clientes
              uri: lb://msclientes
              predicates:
                - Path=/api/clientes/**
            - id: msclientes-direcciones
              uri: lb://msclientes
              predicates:
                - Path=/api/direcciones/**
            - id: msvehiculos-vehiculos
              uri: lb://msvehiculos
              predicates:
                - Path=/api/vehiculos/**
            - id: msvehiculos-categorias
              uri: lb://msvehiculos
              predicates:
                - Path=/api/categorias/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
